spring:
  server:
    port: 8080
  application:
    name: stuManage
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库连接驱动
    username: root
    password: 123456
    url: jdbc:mysql://stuManage-database:3306/student_info?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rs.stuManage.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl